#pragma once

#include "antlr4-runtime.h"
#include "exceptions/same_nested_variable_exception.hpp"
#include "parsing/variable_catalog.hpp"
#include "parsing/grammar/autogenerated/REmatchParserBaseVisitor.h"
#include "exceptions/multi_spanners_not_allowed_exception.hpp"
#include "exceptions/unbalanced_nested_variables_exception.hpp"
#include "exceptions/unbalanced_variables_exception.hpp"
#include "exceptions/unbalanced_disjunction_exception.hpp"

// #define VARIABLE_CATALOG_VISITOR__DEBUG
#ifdef VARIABLE_CATALOG_VISITOR__DEBUG
#define VARIABLE_CATALOG_VISITOR__INFO(arg) std::cout << arg
#else
#define VARIABLE_CATALOG_VISITOR__INFO(arg)
#endif

namespace rematch {
namespace visitors {

class VariableCatalogVisitor : public REmatchParserBaseVisitor {
public:
  std::shared_ptr<VariableCatalog> vfact_ptr;
  std::string regex;

  void set_allow_multi_spanners(bool allow_multi_spanners) {
    allow_multi_spanners_ = allow_multi_spanners;
  }

  std::any visitRoot(REmatchParser::RootContext *ctx) override {
    regex = ctx->getText();
    std::any vfact = visit(ctx->alternation());
    VariableCatalog& vfact_cast = std::any_cast<VariableCatalog &>(vfact);
    if (allow_multi_spanners_){
      vfact_cast.check_nested();
    } else {
      // vfact_cast.check_left_side();
      // Check all single variables are paired
      vfact_cast.check_edges();
    }
    // std::cout << "variables left" << " " << vfact_cast.size_left() << std::endl;
    vfact_ptr = std::make_shared<VariableCatalog>(vfact_cast);

    return 0;
  }
private:
  bool allow_multi_spanners_ = false;

  std::any visitAlternation(REmatchParser::AlternationContext *ctx) override {
    // std::cout << "alternation" << " " << ctx->getText() << " " << ctx->expr().size() << std::endl;
    VARIABLE_CATALOG_VISITOR__INFO("visitAlternation" << std::endl;);
    std::any vfact = visit(ctx->expr().front());
    VariableCatalog &vfact_cast = std::any_cast<VariableCatalog &>(vfact);

    size_t children_size = ctx->expr().size();
    if (children_size > 1) {
      for (size_t i = 1; i < children_size; i++) {
        std::any rhs = visit(ctx->expr(i));
        VariableCatalog &rhs_cast = std::any_cast<VariableCatalog &>(rhs);
        if (!allow_multi_spanners_ && rhs_cast.variables() != vfact_cast.variables()) {
          throw REMatch::MultiSpannersNotAllowedException();
        }
        vfact_cast.merge(rhs_cast);
        if (allow_multi_spanners_){
          vfact_cast.nested_alternation(rhs_cast);
        }
        else {
          if (rhs_cast.left_variables() != vfact_cast.left_variables() || rhs_cast.right_variables() != vfact_cast.right_variables()){
            throw REMatch::UnbalancedDisjunctionException();
          }
        }
      }
    }

    return vfact;
  }

  std::any visitExpr(REmatchParser::ExprContext *ctx) override {
    VARIABLE_CATALOG_VISITOR__INFO("visitExpr" << std::endl;);
    std::any vfact = visit(ctx->element().front());
    VariableCatalog &vfact_cast = std::any_cast<VariableCatalog &>(vfact);

    size_t children_size = ctx->element().size();
    if (children_size > 1) {
      for (size_t i = 1; i < children_size; i++) {
        std::any rhs = visit(ctx->element()[i]);
        VariableCatalog &rhs_cast = std::any_cast<VariableCatalog &>(rhs);

        if (allow_multi_spanners_) {
          vfact_cast.merge(rhs_cast);
          vfact_cast.nested_expr(rhs_cast);
        } else {
          vfact_cast.merge_disjoint(rhs_cast);
        }
      }
    }

    return vfact;
  }

  std::any visitElement(REmatchParser::ElementContext *ctx) override {
    // std::cout << "element" << " " << ctx->getText() << std::endl;
    VARIABLE_CATALOG_VISITOR__INFO("visitElement" << std::endl;);
    std::any vfact = visit(ctx->group());
    VariableCatalog &vfact_cast = std::any_cast<VariableCatalog &>(vfact);

    if (!vfact_cast.empty() && ctx->quantifier() && !allow_multi_spanners_) {
      throw REMatch::MultiSpannersNotAllowedException();
    }

    if (ctx->quantifier()) {
      if (ctx->quantifier()->STAR() || ctx->quantifier()->QUESTION()) {
        vfact_cast.set_empty_word_value(true);
      }
      else if (ctx->quantifier()->quantity()){
        if (ctx->quantifier()->quantity()->quantMax()){
          vfact_cast.set_empty_word_value(true);
        }
      }
    }
    if (allow_multi_spanners_) {
      // if (ctx->quantifier()) {
        // if (ctx->quantifier()->quantity()->quantExact()) {
        //   vfact_cast.quantity_nested(std::stoi(ctx->quantifier()->quantity()->quantExact()->getText()));
        // }
        // else if (ctx->quantifier()->quantity()->quantRange() || ctx->quantifier()->PLUS()) {
        //   for (auto& kv : vfact_cast.variable_balance()) {
        //     if (kv.second.first != kv.second.second) {
        //       throw REMatch::UnbalancedNestedVariablesException();
        //     }
        //   }
        // }
        // else {
        //   for (auto& kv : vfact_cast.variable_balance()) {
        //     if (kv.second != std::pair<uint_fast32_t, uint_fast32_t> (0, 0)) {
        //       throw REMatch::UnbalancedNestedVariablesException();
        //     }
        //   }
        // }
      // }
      for (auto& kv : vfact_cast.variable_balance()) {
        if (ctx->quantifier()) {
          if (kv.second != std::pair<uint_fast32_t, uint_fast32_t> (0, 0)) {
            throw REMatch::UnbalancedNestedVariablesException();
          }
        }
        else {
          if (!((kv.second.first == 0 || kv.second.first == 1) && (kv.second.second == 0 || kv.second.second == 1))) {
            throw REMatch::UnbalancedNestedVariablesException();
          }
        }
      }
    }
    return vfact;
  }

  std::any visitGroup(REmatchParser::GroupContext *ctx) override {
    // std::cout << "group" << " " << ctx->getText() << std::endl;
    VARIABLE_CATALOG_VISITOR__INFO("visitGroup" << std::endl;);
    std::any vfact;

    if (ctx->parentheses()) {
      vfact = visit(ctx->parentheses());
    } else if (ctx->assignation()) {
      vfact = visit(ctx->assignation());
    } else {
      vfact = visit(ctx->atom());
    }

    return vfact;
  }

  std::any visitParentheses(REmatchParser::ParenthesesContext *ctx) override {
    // std::cout << "parentheses" << " " << ctx->getText() << std::endl;
    VARIABLE_CATALOG_VISITOR__INFO("visitParentheses" << std::endl;);
    return visit(ctx->alternation());
  }

  std::any visitAssignation(REmatchParser::AssignationContext *ctx) override {
    // std::cout << "assignation" << " " << ctx->getText() << std::endl;
    VARIABLE_CATALOG_VISITOR__INFO("visitAssignation" << std::endl;);
    std::any vfact = visit(ctx->alternation());
    VariableCatalog &vfact_cast = std::any_cast<VariableCatalog &>(vfact);

    std::string var = ctx->varname()->getText();
    if (vfact_cast.contains(var)) {
      auto interval = ctx->getSourceInterval();
      throw REMatch::SameNestedVariableException(var, regex, interval.a);
    }
    vfact_cast.add(var);

    return vfact;
  }

  std::any visitLeftAssignation(REmatchParser::LeftAssignationContext *ctx) override {
    // std::cout << "left assignation" << " " << ctx->getText() << std::endl;
    VARIABLE_CATALOG_VISITOR__INFO("visitLeftAssignation" << std::endl;);
    auto vfact = std::make_any<VariableCatalog>();
    VariableCatalog &vfact_cast = std::any_cast<VariableCatalog&>(vfact);

    std::string var = ctx->varname()->getText();
    vfact_cast.add_single(var, true);
    if (allow_multi_spanners_){
      vfact_cast.set_nested(var, 1, 0);
    }

    return vfact;
  }

  std::any visitRightAssignation(REmatchParser::RightAssignationContext *ctx) override {
    // std::cout << "right assignation" << " " << ctx->getText() << std::endl;
    VARIABLE_CATALOG_VISITOR__INFO("visitRightAssignation" << std::endl;);
    auto vfact = std::make_any<VariableCatalog>();
    VariableCatalog &vfact_cast = std::any_cast<VariableCatalog&>(vfact);

    std::string var = ctx->varname()->getText();
    vfact_cast.add_single(var, false);
    if (allow_multi_spanners_){
      vfact_cast.set_nested(var, 0, 1);
    }

    return vfact;
  }

  std::any visitAtom(REmatchParser::AtomContext *ctx) override {
    // std::cout << "atom" << " " << ctx->getText() << std::endl;
    VARIABLE_CATALOG_VISITOR__INFO("visitAtom" << std::endl;);
    std::any vfact;

    if (ctx->leftAssignation()) {
      vfact = visit(ctx->leftAssignation());
    } else if (ctx->rightAssignation()) {
      vfact = visit(ctx->rightAssignation());
    } else {
      auto vfact = std::make_any<VariableCatalog>();
      VariableCatalog &vfact_cast = std::any_cast<VariableCatalog&>(vfact);
      vfact_cast.set_empty_word_value(false);
      return vfact;
    }

    return vfact;
  }
  // std::any visitAtom(REmatchParser::AtomContext*) override {
  //   VARIABLE_CATALOG_VISITOR__INFO("visitAtom" << std::endl;);
  //   return std::make_any<VariableCatalog>();
  // }
};
} // namespace visitors
} // namespace rematch
